# Generated by Django 5.2 on 2025-05-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
    ]
