# Generated by Django 5.2 on 2025-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('course', 'is_final'), name='unique_final_quiz_per_course'),
        ),
    ]
