# Generated by Django 5.2 on 2025-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0003_quiz_unique_final_quiz_per_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teams', to='lms_backend.course'),
        ),
    ]
